
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dadistf.c dainterpf.c dacornf.c dasubf.c dageometryf.c daf.c dagtolf.c gr1f.c dagetarrayf.c dagetelemf.c daddf.c fddaf.c dacreatef.c daindexf.c dagtonaf.c dapreallocatef.c dalocalf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
