
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = iscompf.c isdifff.c isblockf.c iscoloringf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	  = libpetscvec
LOCDIR	  = src/vec/is/is/utils/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
