
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dviewpf.c drectf.c dmarkerf.c dellipsef.c dpointf.c dmousef.c dclearf.c dtextf.c dcoorf.c drawregf.c dsavef.c dpausef.c dtrif.c drawf.c dflushf.c dlinef.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscsys
LOCDIR    = src/sys/classes/draw/interface/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
